### ISSUE TITLE
Create a Login 

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#10]
## Create a Login 

-> Create a Login button in Header and Create Login page for website

**Comment by preciousjohn** [comment]
Hello, please can you assign this to me

**Comment by preciousjohn** [comment]
Hello,
I've completed this. I will also appreciate your feedback
Thank you for assigning this to me

**Comment by manapureanshul7** [comment]
Is this issue closed?

**Comment by krushnadurole** [comment]
I would like to contribute on this . 
can you please assign these to me ?

**Comment by prajwald2607** [comment]
I would like to contribute on this, Please assign this issue to me !!

**Comment by ranjitodedra** [comment]
> I would like to contribute on this, Please assign this issue to me !!

@prajwald2607 you can start working on this issue
