### ISSUE TITLE
Create hero 

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#11]
## Create Hero part of the website 

- here you have to write "Scale your content with Trendit" on the left side.

-  then write  " Trendit helps creators to grow faster "

-  on the side put a vector image related to the growth 

- put a get started button in dark of bootrap

**Comment by galbwe** [comment]
Hi! Can I work on this issue?

**Comment by ranjitodedra** [comment]
> Hi! Can I work on this issue?

you can start working on it
