### ISSUE TITLE
Create a section 

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#12]
# Create a Section in Home Component for "Internet Trends"
 

 - in this section, I think we will fetch keywords which trending all over the internet

# 🎯Goal 
1.  Create a section after the hero part of the website
2.  Write any for words (name of cars) in such a way that it covers the maximum page area 
3. it doesn't mean you that you have to increase font size

**Comment by DevTomilola-OS** [comment]
I'll like to know info to be included in section, kindly assign to me.

**Comment by ranjitodedra** [comment]
> I'll like to know info to be included in section, kindly assign to me.

Here you have 

Internet Trends -> title
Keyword1 -> content
Keyword2
Keyword3
Keyword4

Make for these latter we will replace it by back-end
