### ISSUE TITLE
About Us page 

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#13]
# Create an about us page 

-> take data from readme of definition and purpose from that written content in about me page 
-> make it simple follow white and dark theme

**Comment by Soumyajit2825** [comment]
@ranjitodedra assign me to do it

**Comment by Vedant755** [comment]
Can I work on the issue? I have worked on readme pages and have a piece of good knowledge about them.

**Comment by prajwald2607** [comment]
I would like to contribute on this, Please assign this issue to me !!

**Comment by tanyaa-arora** [comment]
hi @ranjitodedra I'd like to do this task. Kindly assign it to me

**Comment by ranjitodedra** [comment]
> hi @ranjitodedra I'd like to do this task. Kindly assign it to me 

@tanyaa-arora you can start working on it

**Comment by shyamaljoshi1** [comment]
assign it to me I have done it 
![image](https://user-images.githubusercontent.com/78912014/196185298-179101c5-b7df-4a2d-8de6-a59262bcce3d.png)

**Comment by ranjitodedra** [comment]
> assign it to me I have done it ![image](https://user-images.githubusercontent.com/78912014/196185298-179101c5-b7df-4a2d-8de6-a59262bcce3d.png)

Good Mr.Joshi
