### ISSUE TITLE
Create page for Trends 

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#15]
# Create Page for Google Trends 

- Create a page where you have to give heading as google trends 

- in this page, we will just fetch 10 keywords 

- use your creativity to make the page look having so less content

**Comment by Candy505** [comment]
@ranjitodedra I am lil unsure but I would like to work on this, the main focus is on the look of the page right ?

**Comment by ranjitodedra** [comment]
> @ranjitodedra I am lil unsure but I would like to work on this, the main focus is on the look of the page right ?
> 

Yes
