### ISSUE TITLE
add logo

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#17]
# Add logo 🎯

- you have add logo to the header 

- you can find logo from asset/logo

- but here you have to crop text part because I want just icon there

- Make this Tredit.com --> TRENDIT

**Comment by deepak-1999** [comment]
Hey @ranjitodedra, Assign this to me

**Comment by deepak-1999** [comment]
Thanks @ranjitodedra

**Comment by deepak-1999** [comment]
Hey @ranjitodedra, Raised this PR ([Link](https://github.com/clubgamma/Trendit/pull/20)), Please review
