### ISSUE TITLE
create api

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#26]
- create login api in sever

**Comment by krushnadurole** [comment]
I have experience in creating login api , i would like to contribute , please assign

**Comment by ranjitodedra** [comment]
> I have experience in creating login api , i would like to contribute , please assign
> 

@krushnadurole you can start work.

**Comment by krushnadurole** [comment]
please mentioned it  as hectober accepted i mean add hectoberfest labels
