### ISSUE TITLE
About US page is not Working 

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#30]
# About Us page 

- Remove keywords like descriptions and purpose 

- add some additional things with your creativity

- take care of both themes

**Comment by AnonymousSudh** [comment]
what you exactly want in about us. page?
i may try this project and take care of theme also.. just told me what you exactly want in about us?

**Comment by ranjitodedra** [comment]
> what you exactly want in about us. page?
> i may try this project and take care of theme also.. just told me what you exactly want in about us?

You just need to remove word purpose and definition and add an vector image related to growth 📈

**Comment by Ankit-34** [comment]
I would like to work on this issue.
