### ISSUE TITLE
add Favicon

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#32]
# create and app favicon

- Use the logo as a reference

**Comment by AmanPathan** [comment]
I can work on this issue

**Comment by abhishekpatil4** [comment]
@ranjitodedra Assign me this task, will get it done in no time. I'm a full-stack developer (MERN Stack). please describe how you want the favicon to look (📈 something like this?)

**Comment by ranjitodedra** [comment]
> @ranjitodedra Assign me this task, will get it done in no time. I'm a full-stack developer (MERN Stack). please describe how you want the favicon to look (📈 something like this?)

Check out logo in asset folder 📁

**Comment by abhishekpatil4** [comment]
@ranjitodedra found it, assign me the issue and I will get started asap

**Comment by abhishekpatil4** [comment]
@ranjitodedra I'm getting this error while installing the dependencies,  please help me with this

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/abhishekpatil/Documents/VScode Files/Web Development/hacktoberfest/Trendit/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/abhishekpatil/Documents/VScode Files/Web Development/hacktoberfest/Trendit/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abhishekpatil/.npm/_logs/2022-10-18T04_45_33_001Z-debug-0.log

**Comment by ranjitodedra** [comment]
> @ranjitodedra I'm getting this error while installing the dependencies,  please help me with this
> 
> npm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path /Users/abhishekpatil/Documents/VScode Files/Web Development/hacktoberfest/Trendit/package.json
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, open '/Users/abhishekpatil/Documents/VScode Files/Web Development/hacktoberfest/Trendit/package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/abhishekpatil/.npm/_logs/2022-10-18T04_45_33_001Z-debug-0.log

U need to reinstall it.
it happens sometimes when dependencies are not installed properly !

**Comment by abhishekpatil4** [comment]
@ranjitodedra I've done the changes mentioned, please verify my pull request and let me know if any changes to be made.
