### ISSUE TITLE
Add 2d illustration

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#35]
## Add any 2d illustration On the Home page.

- Use FreePik.com

- Any 2d Illustration that represents Growth

- Keep size in your mind 

- Also take care of Dark Theme

**Comment by disha100** [comment]
@ranjitodedra 

i would like to work on this please assigned it to me

**Comment by shyamaljoshi1** [comment]
If no one is doing this I want to contribute to this issue
