### ISSUE TITLE
add footer

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#4]
# ADD Footer

- add a simple footer section to website

**Comment by georgioupanayiotis** [comment]
@ranjitodedra  can you assign me this task ?

**Comment by aniket2003** [comment]
@ranjitodedra  can you please assign me with this task I would like to do it .

**Comment by Yh010** [comment]
i would like to work on this issue

**Comment by ranjitodedra** [comment]
> @ranjitodedra can you assign me this task ?

@georgioupanayiotis you can start working on it

**Comment by Igdtuwresource** [comment]
@ranjitodedra I can surely do this task without any errors. Can you please assign me the task?

**Comment by georgioupanayiotis** [comment]
Created the PR here https://github.com/clubgamma/Trendit/pull/5

it would be very helpful if you can please review it as soon as possible and merge it or label it as "hacktoberfest-accepted"

**Comment by georgioupanayiotis** [comment]
![Screenshot 2022-10-03 at 11 26 02 AM](https://user-images.githubusercontent.com/1752156/193533012-d22596cf-bb28-4e1d-b70e-f27794d26128.png)

**Comment by georgioupanayiotis** [comment]
@ranjitodedra 
can you please add `hacktoberfest-accepted` label on my PR https://github.com/clubgamma/Trendit/pull/5
