### ISSUE TITLE
Create SignUp page

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#45]
# Create a SignUP page

### Goal  🎯
- [ ] create NavLink which points to the Login page (In case the User doesn't log in).
- [ ] create a simple and modern signup page for the website.
- [ ] take care of dark theme 

### references 🔗
- [bootstrap](https://getbootstrap.com/)
- [dribble](https://dribbble.com/)

### notice 🔔
- Use the same code for login also

**Comment by Ankit-34** [comment]
I think I can  work on this issue! Kindly assign it to me!!
