### ISSUE TITLE
Create a Button for dark mode in header

### ISSUE THREAD

**Issue by ranjitodedra** [clubgamma/Trendit#9]
# Create a Button for dark mode in the header

- you can use bootstrap

- or you can use simple CSS

**Comment by Aman0786-git** [comment]
Can you please assign me this

**Comment by ranjitodedra** [comment]
> Can you please assign me this 

you can start working on it

**Comment by Albert-2** [comment]
hey can you assigned it to me....!!

**Comment by seanysean** [comment]
I'm currently working on this 👍
